"""Validate the self-contained manuscript submission package.

The validator checks the generated package directory and zip archive before the
files are sent to a journal system. It verifies exact file membership, manifest
roles, checksums, and exclusion of local data, outputs, cache files, and secrets.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import re
import subprocess
import sys
import zipfile
from pathlib import Path


LOGGER = logging.getLogger(__name__)
MANUSCRIPT_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_ROOT = Path(__file__).resolve().parent
if str(SCRIPT_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPT_ROOT))
from submission_metadata_checks import (
    COMMIT_PATTERN,
    DKE_ELSEVIER_FILE_REQUIREMENT_ERROR,
    DOI_PATTERN,
    FINAL_UPLOAD_REPOSITORY_BRANCH,
    check_final_upload_cover_letter_text as check_structured_final_upload_cover_letter_text,
    check_final_upload_metadata_text as check_structured_final_upload_metadata_text,
    check_non_placeholder_url,
    doi_from_url,
    scalar_value,
    target_journal_requires_elsevier_files,
)
from validate_artifact_release import (
    DEFAULT_TEMPLATE_PATH as DEFAULT_ARTIFACT_MANIFEST_TEMPLATE_PATH,
    validate_artifact_release as validate_external_artifact_release,
)

DEFAULT_PACKAGE_DIR = MANUSCRIPT_ROOT / "build" / "submission_package"
DEFAULT_ZIP_PATH = MANUSCRIPT_ROOT / "build" / "iad-risk-submission-package.zip"
DEFAULT_DKE_PREFLIGHT_PACKAGE_DIR = MANUSCRIPT_ROOT / "build" / "dke_preflight_package"
DEFAULT_DKE_PREFLIGHT_ZIP_PATH = MANUSCRIPT_ROOT / "build" / "iad-risk-dke-preflight-package.zip"
PACKAGE_ROOT_NAME = "submission_package"
PUBLIC_ARTIFACT_ACCESS_STATUSES = {
    "public",
    "published",
    "publicly_accessible",
    "archived",
}
BASE_EXPECTED_FILES = {
    "main.tex",
    "supplementary_material.tex",
    "references.bib",
    "cover_letter.md",
    "highlights.md",
    "keywords.md",
    "submission_metadata.yml",
    "iad-risk-manuscript-latex.pdf",
    "iad-risk-supplementary-material.pdf",
    "submission_manifest.json",
    "checksums.sha256",
}
DKE_PREFLIGHT_EXPECTED_FILES = {
    "iad-risk-manuscript-elsevier.tex",
    "iad-risk-manuscript-elsevier.pdf",
}
BASE_EXPECTED_MANIFEST_ROLES = {
    "main_latex_source",
    "supplementary_latex_source",
    "bibliography",
    "cover_letter",
    "submission_highlights",
    "submission_keywords",
    "submission_metadata",
    "main_pdf",
    "supplementary_pdf",
}
DKE_PREFLIGHT_EXPECTED_MANIFEST_ROLES = {
    "dke_elsevier_latex_source",
    "dke_elsevier_pdf",
}
BASE_PDF_FRESHNESS_DEPENDENCIES = {
    "iad-risk-manuscript-latex.pdf": ["main.tex", "references.bib"],
    "iad-risk-supplementary-material.pdf": ["supplementary_material.tex"],
}
DKE_PREFLIGHT_PDF_FRESHNESS_DEPENDENCIES = {
    "iad-risk-manuscript-elsevier.pdf": ["iad-risk-manuscript-elsevier.tex", "keywords.md", "references.bib"],
}
EXPECTED_MANIFEST_TOP_LEVEL_FIELDS = {
    "package_name",
    "package_type",
    "submission_stage",
    "description",
    "anonymization",
    "journal_template",
    "reproducibility_level",
    "claim_boundary",
    "source_control",
    "files",
    "excluded",
}
FORBIDDEN_ZIP_PARTS = {
    "data",
    "outputs",
    "__pycache__",
    ".pytest_cache",
    ".git",
}
FORBIDDEN_NAME_FRAGMENTS = [
    ".env",
    ".secret",
    "remote_connection",
    "api_key",
]
TEXT_HYGIENE_SUFFIXES = {
    ".bib",
    ".json",
    ".md",
    ".sha256",
    ".tex",
    ".txt",
    ".yml",
}
ALWAYS_FORBIDDEN_CONTENT_PATTERNS = [
    (re.compile(r"/Users/[^\s{}<>\"']+"), "local macOS absolute path"),
    (re.compile(r"\bfile://[^\s{}<>\"']+", re.IGNORECASE), "local file URI"),
    (re.compile(r"\b(?:Codex|ChatGPT|Claude|OpenAI|GPT|LLM)\b", re.IGNORECASE), "AI/tool trace"),
    (re.compile(r"\b(?:AI-assisted|AI-generated|generated by AI)\b", re.IGNORECASE), "AI/tool trace"),
    (
        re.compile(r"(?:AI\s*辅助|AI\s*生成|已修改|修改记录|工作记录|工作总结|本次修改|本轮修改|处理记录|变更记录)"),
        "process-note trace",
    ),
]
ANONYMOUS_ONLY_FORBIDDEN_CONTENT_PATTERNS = [
    (
        re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"),
        "email address in anonymous package",
    ),
    (re.compile(r"\b\d{4}-\d{4}-\d{4}-\d{3}[0-9X]\b"), "ORCID in anonymous package"),
    (re.compile(r"\bgithub\.com/bujiuzhi\b", re.IGNORECASE), "personal repository URL in anonymous package"),
    (re.compile(r"\bbujiuzhi\b", re.IGNORECASE), "personal account name in anonymous package"),
]
def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments.

    参数:
        无。

    返回:
        argparse.Namespace: Parsed command-line arguments.
    """
    parser = argparse.ArgumentParser(description="Validate a generated journal submission package.")
    parser.add_argument("--package-dir", default=str(DEFAULT_PACKAGE_DIR), help="Generated package directory.")
    parser.add_argument("--zip-path", default=str(DEFAULT_ZIP_PATH), help="Generated package zip path.")
    parser.add_argument("--final-upload", action="store_true", help="Require target journal and real author metadata.")
    parser.add_argument("--dke-preflight", action="store_true", help="Validate a DKE/Elsevier preflight package.")
    parser.add_argument(
        "--artifact-dir",
        default="",
        help="Optional external artifact release directory to cross-check repository commit during final upload.",
    )
    parser.add_argument(
        "--artifact-manifest-template",
        default=str(DEFAULT_ARTIFACT_MANIFEST_TEMPLATE_PATH),
        help="Artifact release manifest template used when --artifact-dir is provided.",
    )
    parser.add_argument(
        "--source-root",
        default=str(MANUSCRIPT_ROOT),
        help="Current manuscript source root used to reject stale generated packages.",
    )
    parser.add_argument("--log-level", default="INFO", help="Logging level.")
    return parser.parse_args()


def run_git_command(repository_root: Path, args: list[str]) -> str:
    """Run a Git command and return stdout.

    参数:
        repository_root: Repository root directory.
        args: Git command arguments after `git`.

    返回:
        str: Stripped stdout, or an empty string when Git is unavailable.
    """
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=repository_root,
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return ""
    if completed.returncode != 0:
        return ""
    return completed.stdout.strip()


def collect_current_source_control_state(source_root: Path) -> dict:
    """Collect the current Git source-control state for package freshness checks.

    参数:
        source_root: Current manuscript source root.

    返回:
        dict: Current source-control metadata, or unavailable metadata outside Git.
    """
    repository_root = source_root.parent
    repository_commit = run_git_command(repository_root, ["rev-parse", "HEAD"])
    repository_branch = run_git_command(repository_root, ["rev-parse", "--abbrev-ref", "HEAD"]) if repository_commit else ""
    porcelain_status = run_git_command(repository_root, ["status", "--porcelain"]) if repository_commit else ""
    if not repository_commit:
        return {
            "available": False,
            "repository_commit": "",
            "repository_branch": "",
            "worktree_dirty": None,
            "tracked_state": "unavailable",
        }
    worktree_dirty = bool(porcelain_status)
    return {
        "available": True,
        "repository_commit": repository_commit,
        "repository_branch": repository_branch,
        "worktree_dirty": worktree_dirty,
        "tracked_state": "dirty" if worktree_dirty else "clean",
    }


def expected_files(dke_preflight: bool = False) -> set[str]:
    """Return expected package file names for a package profile.

    参数:
        dke_preflight: Whether the package should include DKE/Elsevier files.

    返回:
        set[str]: Expected package file names.
    """
    files = set(BASE_EXPECTED_FILES)
    if dke_preflight:
        files.update(DKE_PREFLIGHT_EXPECTED_FILES)
    return files


def expected_manifest_roles(dke_preflight: bool = False) -> set[str]:
    """Return expected manifest roles for a package profile.

    参数:
        dke_preflight: Whether the package should include DKE/Elsevier roles.

    返回:
        set[str]: Expected manifest roles.
    """
    roles = set(BASE_EXPECTED_MANIFEST_ROLES)
    if dke_preflight:
        roles.update(DKE_PREFLIGHT_EXPECTED_MANIFEST_ROLES)
    return roles


def sha256_bytes(content: bytes) -> str:
    """Compute a SHA256 checksum for bytes.

    参数:
        content: File bytes.

    返回:
        str: Hexadecimal SHA256 digest.
    """
    return hashlib.sha256(content).hexdigest()


def sha256_file(path: Path) -> str:
    """Compute a SHA256 checksum for a file.

    参数:
        path: File path.

    返回:
        str: Hexadecimal SHA256 digest.
    """
    return sha256_bytes(path.read_bytes())


def parse_checksums(text: str) -> dict[str, str]:
    """Parse a checksums.sha256 text file.

    参数:
        text: Checksum file content.

    返回:
        dict[str, str]: Mapping from file name to SHA256 digest.

    异常:
        ValueError: Raised when a checksum line is malformed.
    """
    checksums: dict[str, str] = {}
    for line_number, line in enumerate(text.splitlines(), start=1):
        if not line.strip():
            continue
        parts = line.split(maxsplit=1)
        if len(parts) != 2:
            raise ValueError(f"malformed checksum line {line_number}: {line}")
        digest, file_name = parts
        if len(digest.strip()) != 64:
            raise ValueError(f"malformed SHA256 digest on line {line_number}: {digest}")
        checksums[file_name.strip()] = digest.strip()
    return checksums


def check_manifest_text(manifest_text: str, dke_preflight: bool = False, final_upload: bool = False) -> list[str]:
    """Check submission manifest structure and roles.

    参数:
        manifest_text: JSON manifest content.
        dke_preflight: Whether the package should include DKE/Elsevier files.
        final_upload: Whether the package should be marked for final journal upload.

    返回:
        list[str]: Error messages.
    """
    errors: list[str] = []
    try:
        manifest = json.loads(manifest_text)
    except json.JSONDecodeError as exc:
        return [f"submission_manifest.json is invalid JSON: {exc}"]
    missing_fields = EXPECTED_MANIFEST_TOP_LEVEL_FIELDS - set(manifest)
    if missing_fields:
        errors.append(f"submission_manifest.json missing top-level fields: {sorted(missing_fields)}")
    if manifest.get("package_type") != "journal_submission":
        errors.append("submission_manifest.json package_type must be journal_submission")
    if final_upload:
        expected_stage = "final_journal_upload_preflight"
    elif dke_preflight:
        expected_stage = "dke_elsevier_anonymous_preflight"
    else:
        expected_stage = "template_independent_anonymous_pre_submission"
    if manifest.get("submission_stage") != expected_stage:
        errors.append(f"submission_manifest.json submission_stage must be {expected_stage}")
    anonymization = manifest.get("anonymization")
    expected_author_status = "provided_for_final_upload" if final_upload else "anonymous_placeholder"
    if not isinstance(anonymization, dict) or anonymization.get("author_status") != expected_author_status:
        if final_upload:
            errors.append("submission_manifest.json must record final-upload author metadata status")
        else:
            errors.append("submission_manifest.json must record anonymous author placeholder status")
    journal_template = manifest.get("journal_template")
    expected_target_journal_bound = True if final_upload else False
    if not isinstance(journal_template, dict) or journal_template.get("target_journal_bound") is not expected_target_journal_bound:
        if final_upload:
            errors.append("submission_manifest.json must record that target journal template is bound")
        else:
            errors.append("submission_manifest.json must record that no target journal template is bound")
    elif "target journal document class" not in journal_template.get("final_upload_requirements", []):
        errors.append("submission_manifest.json missing target journal document class final-upload requirement")
    if isinstance(journal_template, dict) and final_upload:
        final_upload_requirements = journal_template.get("final_upload_requirements", [])
        if "artifact release linked" not in final_upload_requirements:
            errors.append("submission_manifest.json missing artifact release linked final-upload requirement")
        if "author biographies and photographs" not in final_upload_requirements:
            errors.append("submission_manifest.json missing author biographies and photographs final-upload requirement")
    if dke_preflight and journal_template.get("dke_elsevier_preflight_included") is not True:
        errors.append("submission_manifest.json must record DKE/Elsevier preflight inclusion")
    reproducibility_level = manifest.get("reproducibility_level")
    if not isinstance(reproducibility_level, dict) or reproducibility_level.get("raw_data_distribution") != "excluded":
        errors.append("submission_manifest.json must record that raw data distribution is excluded")
    claim_boundary = manifest.get("claim_boundary")
    if not isinstance(claim_boundary, dict) or claim_boundary.get("no_broad_method_ranking") is not True:
        errors.append("submission_manifest.json must record the no broad method-ranking claim boundary")
    source_control = manifest.get("source_control")
    if not isinstance(source_control, dict):
        errors.append("submission_manifest.json must record source_control metadata")
    else:
        source_required_fields = {"available", "repository_commit", "repository_branch", "worktree_dirty", "tracked_state"}
        missing_source_fields = source_required_fields - set(source_control)
        if missing_source_fields:
            errors.append(f"submission_manifest.json source_control missing fields: {sorted(missing_source_fields)}")
        if source_control.get("available") is True:
            repository_commit = str(source_control.get("repository_commit", ""))
            if not COMMIT_PATTERN.fullmatch(repository_commit):
                errors.append("submission_manifest.json source_control repository_commit is invalid")
            if source_control.get("tracked_state") not in {"clean", "dirty"}:
                errors.append("submission_manifest.json source_control tracked_state must be clean or dirty")
        elif source_control.get("available") is not False:
            errors.append("submission_manifest.json source_control available must be true or false")
    file_rows = manifest.get("files")
    if not isinstance(file_rows, list):
        return ["submission_manifest.json missing files list"]
    roles = {row.get("role") for row in file_rows if isinstance(row, dict)}
    expected_roles = expected_manifest_roles(dke_preflight)
    missing_roles = expected_roles - roles
    extra_roles = roles - expected_roles
    if missing_roles:
        errors.append(f"submission_manifest.json missing roles: {sorted(missing_roles)}")
    if extra_roles:
        errors.append(f"submission_manifest.json has unexpected roles: {sorted(extra_roles)}")
    for row in file_rows:
        if not isinstance(row, dict):
            errors.append("submission_manifest.json contains a non-object file row")
            continue
        package_path = row.get("package_path")
        if package_path not in expected_files(dke_preflight):
            errors.append(f"submission_manifest.json has unexpected package_path: {package_path}")
    return errors


def check_final_upload_source_control_binding(manifest_text: str, metadata_text: str, location: str) -> list[str]:
    """Check final-upload binding between package Git state and submission metadata.

    参数:
        manifest_text: Submission manifest JSON text.
        metadata_text: Submission metadata YAML text.
        location: Human-readable package location.

    返回:
        list[str]: Error messages for source-control binding drift.
    """
    try:
        manifest = json.loads(manifest_text)
    except json.JSONDecodeError:
        return []
    source_control = manifest.get("source_control")
    if not isinstance(source_control, dict) or source_control.get("available") is not True:
        return []
    errors: list[str] = []
    manifest_commit = str(source_control.get("repository_commit", ""))
    metadata_commit = scalar_value(metadata_text, "repository_commit")
    manifest_branch = str(source_control.get("repository_branch", ""))
    metadata_branch = scalar_value(metadata_text, "repository_branch")
    if metadata_commit and manifest_commit and metadata_commit != manifest_commit:
        errors.append(
            f"{location} final-upload source_control commit {manifest_commit} "
            f"does not match submission_metadata.yml repository_commit {metadata_commit}"
        )
    if metadata_branch and manifest_branch and metadata_branch != manifest_branch:
        errors.append(
            f"{location} final-upload source_control branch {manifest_branch} "
            f"does not match submission_metadata.yml repository_branch {metadata_branch}"
        )
    if manifest_branch and manifest_branch != FINAL_UPLOAD_REPOSITORY_BRANCH:
        errors.append(
            f"{location} final-upload source_control repository_branch must be {FINAL_UPLOAD_REPOSITORY_BRANCH}"
        )
    if source_control.get("worktree_dirty") is True:
        errors.append(f"{location} final-upload source_control worktree_dirty must be false")
    return errors


def check_manifest_source_control_current(manifest_text: str, source_root: Path, location: str) -> list[str]:
    """Check whether package source-control metadata matches the current checkout.

    参数:
        manifest_text: Submission manifest JSON text.
        source_root: Current manuscript source root.
        location: Human-readable package location.

    返回:
        list[str]: Error messages for stale source-control metadata.
    """
    try:
        manifest = json.loads(manifest_text)
    except json.JSONDecodeError:
        return []
    source_control = manifest.get("source_control")
    if not isinstance(source_control, dict) or source_control.get("available") is not True:
        return []
    current_source_control = collect_current_source_control_state(source_root)
    if current_source_control.get("available") is not True:
        return []
    errors: list[str] = []
    manifest_commit = str(source_control.get("repository_commit", "")).strip()
    current_commit = str(current_source_control.get("repository_commit", "")).strip()
    manifest_branch = str(source_control.get("repository_branch", "")).strip()
    current_branch = str(current_source_control.get("repository_branch", "")).strip()
    if manifest_commit != current_commit:
        errors.append(
            f"{location} source_control repository_commit {manifest_commit} does not match "
            f"current repository_commit {current_commit}; rebuild submission package"
        )
    if manifest_branch != current_branch:
        errors.append(
            f"{location} source_control repository_branch {manifest_branch} does not match "
            f"current repository_branch {current_branch}; rebuild submission package"
        )
    if source_control.get("worktree_dirty") != current_source_control.get("worktree_dirty"):
        errors.append(
            f"{location} source_control worktree_dirty {source_control.get('worktree_dirty')} does not match "
            f"current worktree_dirty {current_source_control.get('worktree_dirty')}; rebuild submission package"
        )
    return errors


def check_package_files_match_sources(
    manifest_text: str,
    package_dir: Path,
    source_root: Path,
    final_upload: bool = False,
) -> list[str]:
    """Check whether packaged files match the current source files.

    参数:
        manifest_text: Submission manifest JSON text.
        package_dir: Generated package directory.
        source_root: Current manuscript source root.
        final_upload: Whether final-upload metadata may be generated from source metadata.

    返回:
        list[str]: Error messages for stale or missing package-source files.
    """
    try:
        manifest = json.loads(manifest_text)
    except json.JSONDecodeError:
        return []
    file_rows = manifest.get("files")
    if not isinstance(file_rows, list):
        return []
    errors: list[str] = []
    for row in file_rows:
        if not isinstance(row, dict):
            continue
        package_path_value = row.get("package_path")
        source_path_value = row.get("source_path")
        if not isinstance(package_path_value, str) or not isinstance(source_path_value, str):
            continue
        if final_upload and package_path_value == "submission_metadata.yml":
            continue
        package_path = package_dir / package_path_value
        source_path = source_root / source_path_value
        if not source_path.is_file():
            errors.append(f"{package_dir} current source file is missing: {source_path_value}")
            continue
        if not package_path.is_file():
            continue
        if sha256_file(package_path) != sha256_file(source_path):
            errors.append(
                f"{package_dir} package file {package_path_value} differs from current source "
                f"{source_path_value}; rebuild submission package"
            )
    return errors


def check_zip_files_match_sources(
    manifest_text: str,
    archive: zipfile.ZipFile,
    package_root_name: str,
    source_root: Path,
    final_upload: bool = False,
) -> list[str]:
    """Check whether zipped package files match the current source files.

    参数:
        manifest_text: Submission manifest JSON text from the zip archive.
        archive: Open zip archive.
        package_root_name: Expected root directory inside the zip archive.
        source_root: Current manuscript source root.
        final_upload: Whether final-upload metadata may be generated from source metadata.

    返回:
        list[str]: Error messages for stale or missing zip-source files.
    """
    try:
        manifest = json.loads(manifest_text)
    except json.JSONDecodeError:
        return []
    file_rows = manifest.get("files")
    if not isinstance(file_rows, list):
        return []
    errors: list[str] = []
    for row in file_rows:
        if not isinstance(row, dict):
            continue
        package_path_value = row.get("package_path")
        source_path_value = row.get("source_path")
        if not isinstance(package_path_value, str) or not isinstance(source_path_value, str):
            continue
        if final_upload and package_path_value == "submission_metadata.yml":
            continue
        member_path = f"{package_root_name}/{package_path_value}"
        source_path = source_root / source_path_value
        if not source_path.is_file():
            errors.append(f"zip archive current source file is missing: {source_path_value}")
            continue
        try:
            member_content = archive.read(member_path)
        except KeyError:
            continue
        if sha256_bytes(member_content) != sha256_file(source_path):
            errors.append(
                f"zip archive package file {package_path_value} differs from current source "
                f"{source_path_value}; rebuild submission package"
            )
    return errors


def load_artifact_manifest(artifact_dir: Path | None) -> tuple[dict | None, list[str]]:
    """Load an external artifact release manifest for final-upload cross-checks.

    参数:
        artifact_dir: Optional artifact release directory.

    返回:
        tuple[dict | None, list[str]]: Parsed manifest object and error messages.
    """
    if artifact_dir is None:
        return None, []
    manifest_path = artifact_dir / "manifest.json"
    if not manifest_path.is_file():
        return None, [f"artifact release manifest missing: {manifest_path}"]
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return None, [f"artifact release manifest is invalid JSON: {exc}"]
    if not isinstance(manifest, dict):
        return None, ["artifact release manifest must contain a JSON object"]
    repository = manifest.get("repository")
    if not isinstance(repository, dict):
        return manifest, ["artifact release manifest missing repository object"]
    artifact_commit = str(repository.get("commit", "")).strip()
    if not COMMIT_PATTERN.fullmatch(artifact_commit):
        return manifest, ["artifact release manifest repository.commit is invalid"]
    return manifest, []


def load_validated_artifact_manifest(
    artifact_dir: Path | None,
    artifact_manifest_template_path: Path,
) -> tuple[dict | None, list[str]]:
    """Validate and load an external artifact release manifest.

    参数:
        artifact_dir: Optional artifact release directory.
        artifact_manifest_template_path: Manifest template for artifact validation.

    返回:
        tuple[dict | None, list[str]]: Parsed manifest and validation errors.
    """
    if artifact_dir is None:
        return None, []
    validation_errors = [
        f"artifact release validation failed: {error}"
        for error in validate_external_artifact_release(artifact_dir, artifact_manifest_template_path)
    ]
    manifest, manifest_errors = load_artifact_manifest(artifact_dir)
    return manifest, validation_errors + manifest_errors


def check_final_upload_artifact_source_binding(
    manifest_text: str,
    metadata_text: str,
    artifact_manifest: dict | None,
    location: str,
) -> list[str]:
    """Check final-upload commit binding against an external artifact manifest.

    参数:
        manifest_text: Submission manifest JSON text.
        metadata_text: Submission metadata YAML text.
        artifact_manifest: Optional parsed artifact release manifest.
        location: Human-readable package location.

    返回:
        list[str]: Error messages for package/artifact commit drift.
    """
    if artifact_manifest is None:
        return []
    repository = artifact_manifest.get("repository")
    if not isinstance(repository, dict):
        return []
    artifact_commit = str(repository.get("commit", "")).strip()
    if not COMMIT_PATTERN.fullmatch(artifact_commit):
        return []
    errors: list[str] = []
    metadata_commit = scalar_value(metadata_text, "repository_commit")
    if metadata_commit and metadata_commit != artifact_commit:
        errors.append(
            f"{location} submission_metadata.yml repository_commit {metadata_commit} "
            f"does not match artifact manifest repository.commit {artifact_commit}"
        )
    try:
        manifest = json.loads(manifest_text)
    except json.JSONDecodeError:
        return errors
    source_control = manifest.get("source_control")
    if isinstance(source_control, dict) and source_control.get("available") is True:
        package_commit = str(source_control.get("repository_commit", "")).strip()
        if package_commit and package_commit != artifact_commit:
            errors.append(
                f"{location} source_control commit {package_commit} "
                f"does not match artifact manifest repository.commit {artifact_commit}"
            )
    return errors


def check_final_upload_artifact_publication_binding(
    metadata_text: str,
    artifact_manifest: dict | None,
    location: str,
) -> list[str]:
    """Check final-upload artifact URL/DOI binding against the artifact manifest.

    参数:
        metadata_text: Submission metadata YAML text.
        artifact_manifest: Optional parsed artifact release manifest.
        location: Human-readable package location.

    返回:
        list[str]: Error messages for public artifact link drift.
    """
    if artifact_manifest is None:
        return []
    publication = artifact_manifest.get("publication")
    if not isinstance(publication, dict):
        return [f"{location} artifact manifest missing publication object"]

    errors: list[str] = []
    public_access_status = str(publication.get("public_access_status", "")).strip()
    if public_access_status not in PUBLIC_ARTIFACT_ACCESS_STATUSES:
        errors.append(
            f"{location} artifact manifest publication.public_access_status "
            f"must be one of {sorted(PUBLIC_ARTIFACT_ACCESS_STATUSES)}"
        )

    metadata_url = scalar_value(metadata_text, "artifact_release_url")
    metadata_doi = scalar_value(metadata_text, "artifact_release_doi")
    artifact_url = str(publication.get("artifact_release_url", "")).strip()
    artifact_doi = str(publication.get("artifact_release_doi", "")).strip()

    if not artifact_url and not artifact_doi:
        errors.append(f"{location} artifact manifest publication must record artifact_release_url or artifact_release_doi")
    if artifact_url:
        errors.extend(
            f"{location} artifact manifest publication.{message}"
            for message in check_non_placeholder_url(artifact_url, "artifact_release_url")
        )
    if artifact_doi and DOI_PATTERN.fullmatch(artifact_doi) is None:
        errors.append(f"{location} artifact manifest publication.artifact_release_doi is invalid")

    artifact_url_doi = doi_from_url(artifact_url) if artifact_url else ""
    if artifact_url_doi and artifact_doi and artifact_url_doi.lower() != artifact_doi.lower():
        errors.append(f"{location} artifact manifest publication URL DOI does not match publication DOI")
    if metadata_url and metadata_url != artifact_url:
        errors.append(
            f"{location} submission_metadata.yml artifact_release_url {metadata_url} "
            f"does not match artifact manifest publication.artifact_release_url {artifact_url}"
        )
    if metadata_doi and metadata_doi.lower() != artifact_doi.lower():
        errors.append(
            f"{location} submission_metadata.yml artifact_release_doi {metadata_doi} "
            f"does not match artifact manifest publication.artifact_release_doi {artifact_doi}"
        )
    return errors


def check_file_membership(file_names: set[str], location: str, dke_preflight: bool = False) -> list[str]:
    """Check exact package file membership.

    参数:
        file_names: File names found in a package location.
        location: Human-readable location label.
        dke_preflight: Whether the package should include DKE/Elsevier files.

    返回:
        list[str]: Error messages.
    """
    expected_file_names = expected_files(dke_preflight)
    missing_files = expected_file_names - file_names
    extra_files = file_names - expected_file_names
    errors: list[str] = []
    if missing_files:
        errors.append(f"{location} missing files: {sorted(missing_files)}")
    if extra_files:
        errors.append(f"{location} has unexpected files: {sorted(extra_files)}")
    return errors


def check_final_upload_metadata_text(metadata_text: str) -> list[str]:
    """Check final-upload submission metadata text.

    参数:
        metadata_text: Metadata YAML text.

    返回:
        list[str]: Error messages for unresolved final-upload metadata.
    """
    return check_structured_final_upload_metadata_text(metadata_text)


def check_final_upload_cover_letter_text(cover_letter_text: str, metadata_text: str) -> list[str]:
    """Check final-upload cover letter text against submission metadata.

    参数:
        cover_letter_text: Cover letter Markdown text.
        metadata_text: Metadata YAML text.

    返回:
        list[str]: Error messages for unresolved final-upload cover letter fields.
    """
    return check_structured_final_upload_cover_letter_text(cover_letter_text, metadata_text)


def is_text_hygiene_file(file_name: str) -> bool:
    """Return whether a package file should be scanned as UTF-8 text.

    参数:
        file_name: Package file name.

    返回:
        bool: True when the file should receive text hygiene checks.
    """
    return Path(file_name).suffix.lower() in TEXT_HYGIENE_SUFFIXES


def line_number_for_match(text: str, match_start: int) -> int:
    """Return the one-based line number for a regex match offset.

    参数:
        text: Full text being scanned.
        match_start: Regex match start offset.

    返回:
        int: One-based line number.
    """
    return text.count("\n", 0, match_start) + 1


def check_text_content_hygiene(
    file_name: str,
    text: str,
    location: str,
    final_upload: bool = False,
) -> list[str]:
    """Check text content for local-path, process-note, and anonymous-review leaks.

    参数:
        file_name: Package file name.
        text: UTF-8 file text.
        location: Human-readable package location.
        final_upload: Whether real author metadata is allowed for final upload.

    返回:
        list[str]: Error messages.
    """
    errors: list[str] = []
    patterns = list(ALWAYS_FORBIDDEN_CONTENT_PATTERNS)
    if not final_upload:
        patterns.extend(ANONYMOUS_ONLY_FORBIDDEN_CONTENT_PATTERNS)
    for pattern, label in patterns:
        match = pattern.search(text)
        if match is None:
            continue
        line_number = line_number_for_match(text, match.start())
        errors.append(f"{location}/{file_name} contains {label} on line {line_number}")
    return errors


def check_text_bytes_hygiene(
    file_name: str,
    content: bytes,
    location: str,
    final_upload: bool = False,
) -> list[str]:
    """Decode and check package text bytes for publication hygiene.

    参数:
        file_name: Package file name.
        content: File bytes.
        location: Human-readable package location.
        final_upload: Whether real author metadata is allowed for final upload.

    返回:
        list[str]: Error messages.
    """
    if not is_text_hygiene_file(file_name):
        return []
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError as exc:
        return [f"{location}/{file_name} is not valid UTF-8 text: {exc}"]
    return check_text_content_hygiene(file_name, text, location, final_upload)


def check_forbidden_path_name(path_name: str, location: str) -> list[str]:
    """Check whether a path name contains forbidden paths or fragments.

    参数:
        path_name: Package path or zip member name.
        location: Human-readable location label.

    返回:
        list[str]: Error messages.
    """
    path_parts = set(Path(path_name).parts)
    errors: list[str] = []
    forbidden_parts = FORBIDDEN_ZIP_PARTS & path_parts
    if forbidden_parts:
        errors.append(f"{location} contains forbidden path part {sorted(forbidden_parts)}: {path_name}")
    lowered_name = path_name.lower()
    for fragment in FORBIDDEN_NAME_FRAGMENTS:
        if fragment in lowered_name:
            errors.append(f"{location} contains forbidden name fragment {fragment}: {path_name}")
    return errors


def check_package_pdf_freshness(package_dir: Path, dke_preflight: bool = False) -> list[str]:
    """Check that packaged PDFs are newer than their packaged source dependencies.

    参数:
        package_dir: Generated package directory.
        dke_preflight: Whether the package includes DKE/Elsevier files.

    返回:
        list[str]: Error messages for stale packaged PDFs.
    """
    dependency_map = dict(BASE_PDF_FRESHNESS_DEPENDENCIES)
    if dke_preflight:
        dependency_map.update(DKE_PREFLIGHT_PDF_FRESHNESS_DEPENDENCIES)
    errors: list[str] = []
    for pdf_name, dependency_names in dependency_map.items():
        pdf_path = package_dir / pdf_name
        if not pdf_path.exists():
            continue
        for dependency_name in dependency_names:
            dependency_path = package_dir / dependency_name
            if not dependency_path.exists():
                continue
            try:
                pdf_mtime = pdf_path.stat().st_mtime
                dependency_mtime = dependency_path.stat().st_mtime
            except OSError as exc:
                errors.append(f"cannot stat packaged PDF dependency {pdf_name} vs {dependency_name}: {exc}")
                continue
            if pdf_mtime < dependency_mtime:
                errors.append(f"{package_dir}/{pdf_name} is older than {dependency_name}; rebuild PDF before packaging")
    return errors


def validate_package_directory(
    package_dir: Path,
    final_upload: bool = False,
    dke_preflight: bool = False,
    artifact_manifest: dict | None = None,
    source_root: Path | None = None,
) -> list[str]:
    """Validate the generated package directory.

    参数:
        package_dir: Generated package directory.
        final_upload: Whether to require journal and author metadata for final upload.
        dke_preflight: Whether the package should include DKE/Elsevier files.
        artifact_manifest: Optional external artifact release manifest.
        source_root: Optional current manuscript source root for stale-package checks.

    返回:
        list[str]: Error messages.
    """
    if not package_dir.exists():
        return [f"package directory does not exist: {package_dir}"]
    if not package_dir.is_dir():
        return [f"package path is not a directory: {package_dir}"]
    entries = list(package_dir.iterdir())
    files = [path for path in entries if path.is_file()]
    directories = [path for path in entries if path.is_dir()]
    errors = check_file_membership({path.name for path in files}, str(package_dir), dke_preflight)
    errors.extend(check_package_pdf_freshness(package_dir, dke_preflight))
    if directories:
        errors.append(f"{package_dir} has unexpected directories: {sorted(path.name for path in directories)}")
    for path in entries:
        errors.extend(check_forbidden_path_name(path.name, str(package_dir)))
        if path.is_file():
            errors.extend(check_text_bytes_hygiene(path.name, path.read_bytes(), str(package_dir), final_upload))
    checksums_path = package_dir / "checksums.sha256"
    manifest_path = package_dir / "submission_manifest.json"
    metadata_path = package_dir / "submission_metadata.yml"
    cover_letter_path = package_dir / "cover_letter.md"
    if manifest_path.exists():
        manifest_text = manifest_path.read_text(encoding="utf-8")
        errors.extend(check_manifest_text(manifest_text, dke_preflight, final_upload))
        if source_root is not None:
            errors.extend(check_manifest_source_control_current(manifest_text, source_root, str(package_dir)))
            errors.extend(check_package_files_match_sources(manifest_text, package_dir, source_root, final_upload))
    if final_upload:
        if metadata_path.exists():
            metadata_text = metadata_path.read_text(encoding="utf-8")
            errors.extend(check_final_upload_metadata_text(metadata_text))
            if target_journal_requires_elsevier_files(metadata_text) and not dke_preflight:
                errors.append(DKE_ELSEVIER_FILE_REQUIREMENT_ERROR)
            if manifest_path.exists():
                errors.extend(
                    check_final_upload_source_control_binding(
                        manifest_path.read_text(encoding="utf-8"),
                        metadata_text,
                        str(package_dir),
                    )
                )
                errors.extend(
                    check_final_upload_artifact_source_binding(
                        manifest_path.read_text(encoding="utf-8"),
                        metadata_text,
                        artifact_manifest,
                        str(package_dir),
                    )
                )
                errors.extend(
                    check_final_upload_artifact_publication_binding(
                        metadata_text,
                        artifact_manifest,
                        str(package_dir),
                    )
                )
            if cover_letter_path.exists():
                errors.extend(check_final_upload_cover_letter_text(cover_letter_path.read_text(encoding="utf-8"), metadata_text))
            else:
                errors.append("package directory missing cover_letter.md for final upload")
        else:
            errors.append("package directory missing submission_metadata.yml for final upload")
    if checksums_path.exists():
        try:
            checksums = parse_checksums(checksums_path.read_text(encoding="utf-8"))
        except ValueError as exc:
            errors.append(f"checksums.sha256 is invalid: {exc}")
            checksums = {}
        expected_checksum_files = expected_files(dke_preflight) - {"checksums.sha256"}
        if "checksums.sha256" in checksums:
            errors.append("checksums.sha256 must not include itself")
        missing_checksum_entries = expected_checksum_files - set(checksums)
        extra_checksum_entries = set(checksums) - expected_checksum_files
        if missing_checksum_entries:
            errors.append(f"checksums.sha256 missing entries: {sorted(missing_checksum_entries)}")
        if extra_checksum_entries:
            errors.append(f"checksums.sha256 has unexpected entries: {sorted(extra_checksum_entries)}")
        for file_name in expected_checksum_files & set(checksums):
            file_path = package_dir / file_name
            if file_path.exists() and sha256_file(file_path) != checksums[file_name]:
                errors.append(f"checksum mismatch for package file: {file_name}")
    return errors


def validate_zip_archive(
    zip_path: Path,
    final_upload: bool = False,
    dke_preflight: bool = False,
    package_root_name: str = PACKAGE_ROOT_NAME,
    artifact_manifest: dict | None = None,
    source_root: Path | None = None,
) -> list[str]:
    """Validate the generated package zip archive.

    参数:
        zip_path: Zip archive path.
        final_upload: Whether to require journal and author metadata for final upload.
        dke_preflight: Whether the package should include DKE/Elsevier files.
        package_root_name: Expected root directory name inside the zip archive.
        artifact_manifest: Optional external artifact release manifest.
        source_root: Optional current manuscript source root for stale-package checks.

    返回:
        list[str]: Error messages.
    """
    if not zip_path.exists():
        return [f"zip archive does not exist: {zip_path}"]
    errors: list[str] = []
    try:
        with zipfile.ZipFile(zip_path) as archive:
            member_names = archive.namelist()
            for member_name in member_names:
                errors.extend(check_forbidden_path_name(member_name, "zip archive"))
            expected_prefix = f"{package_root_name}/"
            expected_file_names = expected_files(dke_preflight)
            expected_member_names = {f"{expected_prefix}{file_name}" for file_name in expected_file_names}
            file_member_names = {member_name for member_name in member_names if not member_name.endswith("/")}
            directory_member_names = {member_name for member_name in member_names if member_name.endswith("/")}
            missing_member_names = expected_member_names - file_member_names
            unexpected_member_names = file_member_names - expected_member_names
            unexpected_directory_names = directory_member_names - {expected_prefix}
            if missing_member_names:
                errors.append(f"zip archive missing members: {sorted(missing_member_names)}")
            if unexpected_member_names:
                errors.append(f"zip archive has unexpected members: {sorted(unexpected_member_names)}")
            if unexpected_directory_names:
                errors.append(f"zip archive has unexpected directories: {sorted(unexpected_directory_names)}")
            package_file_names = {
                member_name.removeprefix(expected_prefix)
                for member_name in member_names
                if member_name.startswith(expected_prefix) and not member_name.endswith("/")
            }
            errors.extend(check_file_membership(package_file_names, str(zip_path), dke_preflight))
            for member_name in sorted(file_member_names):
                file_name = (
                    member_name.removeprefix(expected_prefix)
                    if member_name.startswith(expected_prefix)
                    else Path(member_name).name
                )
                if not is_text_hygiene_file(file_name):
                    continue
                try:
                    member_content = archive.read(member_name)
                except KeyError:
                    errors.append(f"zip archive missing text hygiene member: {member_name}")
                    continue
                errors.extend(check_text_bytes_hygiene(file_name, member_content, "zip archive", final_upload))
            try:
                manifest_text = archive.read(f"{package_root_name}/submission_manifest.json").decode("utf-8")
                checksums_text = archive.read(f"{package_root_name}/checksums.sha256").decode("utf-8")
            except KeyError as exc:
                return errors + [f"zip archive missing required metadata file: {exc}"]
            errors.extend(check_manifest_text(manifest_text, dke_preflight, final_upload))
            if source_root is not None:
                errors.extend(check_manifest_source_control_current(manifest_text, source_root, "zip archive"))
                errors.extend(
                    check_zip_files_match_sources(
                        manifest_text,
                        archive,
                        package_root_name,
                        source_root,
                        final_upload,
                    )
                )
            if final_upload:
                try:
                    metadata_text = archive.read(f"{package_root_name}/submission_metadata.yml").decode("utf-8")
                except KeyError as exc:
                    return errors + [f"zip archive missing submission_metadata.yml for final upload: {exc}"]
                errors.extend(check_final_upload_metadata_text(metadata_text))
                if target_journal_requires_elsevier_files(metadata_text) and not dke_preflight:
                    errors.append(DKE_ELSEVIER_FILE_REQUIREMENT_ERROR)
                errors.extend(check_final_upload_source_control_binding(manifest_text, metadata_text, "zip archive"))
                errors.extend(
                    check_final_upload_artifact_source_binding(
                        manifest_text,
                        metadata_text,
                        artifact_manifest,
                        "zip archive",
                    )
                )
                errors.extend(
                    check_final_upload_artifact_publication_binding(
                        metadata_text,
                        artifact_manifest,
                        "zip archive",
                    )
                )
                try:
                    cover_letter_text = archive.read(f"{package_root_name}/cover_letter.md").decode("utf-8")
                except KeyError as exc:
                    return errors + [f"zip archive missing cover_letter.md for final upload: {exc}"]
                errors.extend(check_final_upload_cover_letter_text(cover_letter_text, metadata_text))
            try:
                checksums = parse_checksums(checksums_text)
            except ValueError as exc:
                errors.append(f"zip checksums.sha256 is invalid: {exc}")
                checksums = {}
            expected_checksum_files = expected_file_names - {"checksums.sha256"}
            if "checksums.sha256" in checksums:
                errors.append("zip checksums.sha256 must not include itself")
            missing_checksum_entries = expected_checksum_files - set(checksums)
            extra_checksum_entries = set(checksums) - expected_checksum_files
            if missing_checksum_entries:
                errors.append(f"zip checksums.sha256 missing entries: {sorted(missing_checksum_entries)}")
            if extra_checksum_entries:
                errors.append(f"zip checksums.sha256 has unexpected entries: {sorted(extra_checksum_entries)}")
            for file_name in expected_checksum_files & set(checksums):
                member_path = f"{package_root_name}/{file_name}"
                try:
                    member_content = archive.read(member_path)
                except KeyError:
                    errors.append(f"zip archive missing checksummed file: {member_path}")
                    continue
                if sha256_bytes(member_content) != checksums[file_name]:
                    errors.append(f"zip checksum mismatch for package file: {file_name}")
    except zipfile.BadZipFile as exc:
        errors.append(f"zip archive is invalid: {exc}")
    return errors


def unique_errors(errors: list[str]) -> list[str]:
    """Remove duplicate validation errors while preserving order.

    参数:
        errors: Validation error messages.

    返回:
        list[str]: De-duplicated validation error messages.
    """
    seen_errors: set[str] = set()
    unique_error_list: list[str] = []
    for error in errors:
        if error in seen_errors:
            continue
        seen_errors.add(error)
        unique_error_list.append(error)
    return unique_error_list


def validate_submission_package(
    package_dir: Path,
    zip_path: Path,
    final_upload: bool = False,
    dke_preflight: bool = False,
    artifact_dir: Path | None = None,
    artifact_manifest_template_path: Path = DEFAULT_ARTIFACT_MANIFEST_TEMPLATE_PATH,
    source_root: Path | None = None,
) -> list[str]:
    """Validate the package directory and zip archive.

    参数:
        package_dir: Generated package directory.
        zip_path: Generated zip archive path.
        final_upload: Whether to require journal and author metadata for final upload.
        dke_preflight: Whether the package should include DKE/Elsevier files.
        artifact_dir: Optional external artifact release directory.
        artifact_manifest_template_path: Artifact manifest template used when artifact_dir is provided.
        source_root: Optional current manuscript source root for stale-package checks.

    返回:
        list[str]: Error messages.
    """
    errors: list[str] = []
    if final_upload and artifact_dir is None:
        errors.append("final-upload validation requires --artifact-dir pointing to the finalized artifact release")
    artifact_manifest, artifact_errors = (
        load_validated_artifact_manifest(artifact_dir, artifact_manifest_template_path)
        if final_upload and artifact_dir is not None
        else (None, [])
    )
    errors.extend(artifact_errors)
    errors.extend(validate_package_directory(package_dir, final_upload, dke_preflight, artifact_manifest, source_root))
    errors.extend(validate_zip_archive(
        zip_path,
        final_upload,
        dke_preflight,
        package_dir.name,
        artifact_manifest,
        source_root,
    ))
    return unique_errors(errors)


def main() -> int:
    """Run submission package validation.

    参数:
        无。

    返回:
        int: Process exit code.
    """
    args = parse_arguments()
    logging.basicConfig(level=getattr(logging, args.log_level.upper(), logging.INFO), format="%(levelname)s %(message)s")
    package_dir = Path(args.package_dir)
    zip_path = Path(args.zip_path)
    if args.dke_preflight and package_dir == DEFAULT_PACKAGE_DIR:
        package_dir = DEFAULT_DKE_PREFLIGHT_PACKAGE_DIR
    if args.dke_preflight and zip_path == DEFAULT_ZIP_PATH:
        zip_path = DEFAULT_DKE_PREFLIGHT_ZIP_PATH
    try:
        errors = validate_submission_package(
            package_dir.resolve(),
            zip_path.resolve(),
            args.final_upload,
            args.dke_preflight,
            Path(args.artifact_dir).resolve() if args.artifact_dir else None,
            Path(args.artifact_manifest_template).resolve(),
            Path(args.source_root).resolve() if args.source_root else None,
        )
    except Exception as exc:  # noqa: BLE001
        LOGGER.error("submission package validation failed: %s", exc)
        return 1
    if errors:
        for error in errors:
            LOGGER.error(error)
        return 1
    LOGGER.info("submission package validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
